/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author foraneoblack
 */
public class V_loggins extends javax.swing.JFrame {

    /**
     * Creates new form V_loggins
     */
    public V_loggins() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_Fondo = new FondoPrincipal();
        btn_Iniciar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        btn_cerrar = new javax.swing.JButton();
        txt_Contrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        btn_Iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Iniciar.png"))); // NOI18N
        btn_Iniciar.setBorderPainted(false);
        btn_Iniciar.setContentAreaFilled(false);

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Cerrar-19.png"))); // NOI18N
        btn_cerrar.setBorderPainted(false);
        btn_cerrar.setContentAreaFilled(false);

        javax.swing.GroupLayout jp_FondoLayout = new javax.swing.GroupLayout(jp_Fondo);
        jp_Fondo.setLayout(jp_FondoLayout);
        jp_FondoLayout.setHorizontalGroup(
            jp_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_FondoLayout.createSequentialGroup()
                .addGroup(jp_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_FondoLayout.createSequentialGroup()
                        .addGroup(jp_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_FondoLayout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(btn_Iniciar))
                            .addGroup(jp_FondoLayout.createSequentialGroup()
                                .addGap(265, 265, 265)
                                .addGroup(jp_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(txt_Contrasena))))
                        .addGap(0, 255, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_FondoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_cerrar)))
                .addContainerGap())
        );
        jp_FondoLayout.setVerticalGroup(
            jp_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_cerrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(txt_Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Iniciar)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_Fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Iniciar;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JPanel jp_Fondo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txt_Contrasena;
    // End of variables declaration//GEN-END:variables
 
    class FondoPrincipal extends JPanel{
        private Image imagen;
        
        public void paint(Graphics g){
            imagen=new ImageIcon(getClass().getResource("/Imagenes/Fondo_Inicio.png")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            
            super.paint(g);
        }
       }

    public JButton getBtn_Iniciar() {
        return btn_Iniciar;
    }

    public void setBtn_Iniciar(JButton btn_Iniciar) {
        this.btn_Iniciar = btn_Iniciar;
    }

    public JPasswordField getTxt_Contrasena() {
        return txt_Contrasena;
    }

    public void setTxt_Contrasena(JPasswordField txt_Contrasena) {
        this.txt_Contrasena = txt_Contrasena;
    }


    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public void setTxtNombre(JTextField txtNombre) {
        this.txtNombre = txtNombre;
    }

    public JButton getBtn_cerrar() {
        return btn_cerrar;
    }

    public void setBtn_cerrar(JButton btn_cerrar) {
        this.btn_cerrar = btn_cerrar;
    }

}
