/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author foraneoblack
 */
public class V_mesas extends javax.swing.JFrame {

    /**
     * Creates new form V_mesas
     */
    public V_mesas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_mesas = new FondoMesas();
        btn_mesas = new javax.swing.JButton();
        btn_producto = new javax.swing.JButton();
        btn_cliente = new javax.swing.JButton();
        btn_proveedores = new javax.swing.JButton();
        btn_configuracion = new javax.swing.JButton();
        btn_n1 = new javax.swing.JButton();
        btn_n2 = new javax.swing.JButton();
        btn_n3 = new javax.swing.JButton();
        btn_n4 = new javax.swing.JButton();
        btn_n5 = new javax.swing.JButton();
        btn_n6 = new javax.swing.JButton();
        btn_n7 = new javax.swing.JButton();
        btn_n8 = new javax.swing.JButton();
        btn_n9 = new javax.swing.JButton();
        btn_n10 = new javax.swing.JButton();
        btn_n11 = new javax.swing.JButton();
        btn_n12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_mesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_mesas.png"))); // NOI18N
        btn_mesas.setBorderPainted(false);
        btn_mesas.setContentAreaFilled(false);

        btn_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Productos.png"))); // NOI18N
        btn_producto.setBorderPainted(false);
        btn_producto.setContentAreaFilled(false);

        btn_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Clientes.png"))); // NOI18N
        btn_cliente.setBorderPainted(false);
        btn_cliente.setContentAreaFilled(false);

        btn_proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Proveedores.png"))); // NOI18N
        btn_proveedores.setBorderPainted(false);
        btn_proveedores.setContentAreaFilled(false);

        btn_configuracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Configuracion.png"))); // NOI18N
        btn_configuracion.setBorderPainted(false);
        btn_configuracion.setContentAreaFilled(false);

        btn_n1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_1.png"))); // NOI18N
        btn_n1.setBorderPainted(false);
        btn_n1.setContentAreaFilled(false);

        btn_n2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_2.png"))); // NOI18N
        btn_n2.setBorderPainted(false);
        btn_n2.setContentAreaFilled(false);

        btn_n3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_3.png"))); // NOI18N
        btn_n3.setBorderPainted(false);
        btn_n3.setContentAreaFilled(false);

        btn_n4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_4.png"))); // NOI18N
        btn_n4.setBorderPainted(false);
        btn_n4.setContentAreaFilled(false);

        btn_n5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_5.png"))); // NOI18N
        btn_n5.setBorderPainted(false);
        btn_n5.setContentAreaFilled(false);

        btn_n6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_6.png"))); // NOI18N
        btn_n6.setBorderPainted(false);
        btn_n6.setContentAreaFilled(false);

        btn_n7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_7.png"))); // NOI18N
        btn_n7.setBorderPainted(false);
        btn_n7.setContentAreaFilled(false);

        btn_n8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_8.png"))); // NOI18N
        btn_n8.setBorderPainted(false);
        btn_n8.setContentAreaFilled(false);

        btn_n9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_9.png"))); // NOI18N
        btn_n9.setBorderPainted(false);
        btn_n9.setContentAreaFilled(false);

        btn_n10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_10.png"))); // NOI18N
        btn_n10.setBorderPainted(false);
        btn_n10.setContentAreaFilled(false);

        btn_n11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_11.png"))); // NOI18N
        btn_n11.setBorderPainted(false);
        btn_n11.setContentAreaFilled(false);

        btn_n12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_12.png"))); // NOI18N
        btn_n12.setBorderPainted(false);
        btn_n12.setContentAreaFilled(false);

        javax.swing.GroupLayout jp_mesasLayout = new javax.swing.GroupLayout(jp_mesas);
        jp_mesas.setLayout(jp_mesasLayout);
        jp_mesasLayout.setHorizontalGroup(
            jp_mesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_mesasLayout.createSequentialGroup()
                .addGroup(jp_mesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_mesasLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btn_mesas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btn_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_mesasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_n1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_n2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_n3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_n4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_n5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_n6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_mesasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_n7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_n8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_n9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_n10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_n11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_n12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jp_mesasLayout.setVerticalGroup(
            jp_mesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_mesasLayout.createSequentialGroup()
                .addGroup(jp_mesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_n5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_mesasLayout.createSequentialGroup()
                        .addGroup(jp_mesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_mesas))
                        .addGap(160, 160, 160)
                        .addGroup(jp_mesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_n2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_n1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_n3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_n4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_n6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_mesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_n11, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_n8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_n7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_n9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_n10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_n12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_mesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_mesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cliente;
    private javax.swing.JButton btn_configuracion;
    private javax.swing.JButton btn_mesas;
    private javax.swing.JButton btn_n1;
    private javax.swing.JButton btn_n10;
    private javax.swing.JButton btn_n11;
    private javax.swing.JButton btn_n12;
    private javax.swing.JButton btn_n2;
    private javax.swing.JButton btn_n3;
    private javax.swing.JButton btn_n4;
    private javax.swing.JButton btn_n5;
    private javax.swing.JButton btn_n6;
    private javax.swing.JButton btn_n7;
    private javax.swing.JButton btn_n8;
    private javax.swing.JButton btn_n9;
    private javax.swing.JButton btn_producto;
    private javax.swing.JButton btn_proveedores;
    private javax.swing.JPanel jp_mesas;
    // End of variables declaration//GEN-END:variables
    
    class FondoMesas extends JPanel{
        private Image imagen;
        
        public void paint(Graphics g){
            imagen=new ImageIcon(getClass().getResource("/Imagenes/Fondo_Mesas.png")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            
            super.paint(g);
        }
    }

}
