/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author foraneoblack
 */
public class V_mesas extends javax.swing.JFrame {

    /**
     * Creates new form V_mesas
     */
    public V_mesas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_mesas = new FondoDialogMesas();
        jp_mesas_dialog = new javax.swing.JPanel();
        txt_buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_mesas = new javax.swing.JTable();
        btn_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_factura = new javax.swing.JButton();
        cb_Entrega = new javax.swing.JCheckBox();
        btn_clientes = new javax.swing.JButton();
        txt_idcliente = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_idproducto = new javax.swing.JTable();
        btn_regresar = new javax.swing.JButton();
        dialog_factura = new javax.swing.JDialog();
        jp_factura_dialog = new FondoDialogFactura();
        txt_nombre_d = new javax.swing.JTextField();
        txt_direccion_d = new javax.swing.JTextField();
        txt_ruc_d = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_Factura = new javax.swing.JTable();
        btn_Imprimir = new javax.swing.JButton();
        btn_cancelar_d2 = new javax.swing.JButton();
        dialog_entrega = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        txt_identrega = new javax.swing.JTextField();
        txt_nmesa = new javax.swing.JTextField();
        txt_delivery = new javax.swing.JTextField();
        jp_mesas = new FondoMesas();
        btn_mesas = new javax.swing.JButton();
        btn_producto = new javax.swing.JButton();
        btn_cliente = new javax.swing.JButton();
        btn_Factura = new javax.swing.JButton();
        btn_configuracion = new javax.swing.JButton();
        btn_n1 = new javax.swing.JButton();
        btn_n2 = new javax.swing.JButton();
        btn_n3 = new javax.swing.JButton();
        btn_n4 = new javax.swing.JButton();
        btn_n5 = new javax.swing.JButton();
        btn_n6 = new javax.swing.JButton();
        btn_n7 = new javax.swing.JButton();
        btn_n8 = new javax.swing.JButton();
        btn_n9 = new javax.swing.JButton();
        btn_n10 = new javax.swing.JButton();
        btn_n11 = new javax.swing.JButton();
        btn_n12 = new javax.swing.JButton();
        btn_Reporte = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();

        tb_mesas.setBackground(new java.awt.Color(222, 138, 53));
        tb_mesas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tb_mesas.setForeground(new java.awt.Color(222, 138, 53));
        tb_mesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tb_mesas);
        if (tb_mesas.getColumnModel().getColumnCount() > 0) {
            tb_mesas.getColumnModel().getColumn(1).setHeaderValue("Precio");
        }

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Guardar.png"))); // NOI18N
        btn_guardar.setBorderPainted(false);
        btn_guardar.setContentAreaFilled(false);

        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Cancelar.png"))); // NOI18N
        btn_cancelar.setBorderPainted(false);
        btn_cancelar.setContentAreaFilled(false);

        btn_factura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_factura-13.png"))); // NOI18N
        btn_factura.setBorderPainted(false);
        btn_factura.setContentAreaFilled(false);

        cb_Entrega.setText("Entrega a domicilio");

        btn_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_cliente.png"))); // NOI18N
        btn_clientes.setBorderPainted(false);
        btn_clientes.setContentAreaFilled(false);
        btn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientesActionPerformed(evt);
            }
        });

        tb_idproducto.setBackground(new java.awt.Color(222, 138, 53));
        tb_idproducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tb_idproducto.setForeground(new java.awt.Color(222, 138, 53));
        tb_idproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Id Producto"
            }
        ));
        jScrollPane3.setViewportView(tb_idproducto);

        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_regresar-19.png"))); // NOI18N
        btn_regresar.setBorderPainted(false);
        btn_regresar.setContentAreaFilled(false);

        javax.swing.GroupLayout jp_mesas_dialogLayout = new javax.swing.GroupLayout(jp_mesas_dialog);
        jp_mesas_dialog.setLayout(jp_mesas_dialogLayout);
        jp_mesas_dialogLayout.setHorizontalGroup(
            jp_mesas_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_mesas_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_mesas_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cb_Entrega)
                    .addGroup(jp_mesas_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jp_mesas_dialogLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btn_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(btn_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_idcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_mesas_dialogLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btn_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jp_mesas_dialogLayout.setVerticalGroup(
            jp_mesas_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_mesas_dialogLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jp_mesas_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_mesas_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_clientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(txt_idcliente, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(15, 15, 15)
                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_mesas_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_Entrega)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_mesas_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_regresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialog_mesasLayout = new javax.swing.GroupLayout(dialog_mesas.getContentPane());
        dialog_mesas.getContentPane().setLayout(dialog_mesasLayout);
        dialog_mesasLayout.setHorizontalGroup(
            dialog_mesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_mesasLayout.createSequentialGroup()
                .addComponent(jp_mesas_dialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dialog_mesasLayout.setVerticalGroup(
            dialog_mesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_mesas_dialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tb_Factura.setBackground(new java.awt.Color(222, 138, 53));
        tb_Factura.setForeground(new java.awt.Color(222, 138, 53));
        tb_Factura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cantidad", "Descripcion", "P.Unit", "P.Total"
            }
        ));
        jScrollPane2.setViewportView(tb_Factura);

        btn_Imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_imprimir.png"))); // NOI18N
        btn_Imprimir.setBorderPainted(false);
        btn_Imprimir.setContentAreaFilled(false);

        btn_cancelar_d2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Cancelar.png"))); // NOI18N
        btn_cancelar_d2.setBorderPainted(false);
        btn_cancelar_d2.setContentAreaFilled(false);

        javax.swing.GroupLayout jp_factura_dialogLayout = new javax.swing.GroupLayout(jp_factura_dialog);
        jp_factura_dialog.setLayout(jp_factura_dialogLayout);
        jp_factura_dialogLayout.setHorizontalGroup(
            jp_factura_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_factura_dialogLayout.createSequentialGroup()
                .addGroup(jp_factura_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_factura_dialogLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jp_factura_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ruc_d, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_direccion_d, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombre_d, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp_factura_dialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_factura_dialogLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_cancelar_d2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jp_factura_dialogLayout.setVerticalGroup(
            jp_factura_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_factura_dialogLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(txt_nombre_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_direccion_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_ruc_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(jp_factura_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar_d2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout dialog_facturaLayout = new javax.swing.GroupLayout(dialog_factura.getContentPane());
        dialog_factura.getContentPane().setLayout(dialog_facturaLayout);
        dialog_facturaLayout.setHorizontalGroup(
            dialog_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_factura_dialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialog_facturaLayout.setVerticalGroup(
            dialog_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_factura_dialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_delivery, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(txt_identrega)
                    .addComponent(txt_nmesa))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(txt_identrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_nmesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_delivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout dialog_entregaLayout = new javax.swing.GroupLayout(dialog_entrega.getContentPane());
        dialog_entrega.getContentPane().setLayout(dialog_entregaLayout);
        dialog_entregaLayout.setHorizontalGroup(
            dialog_entregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialog_entregaLayout.setVerticalGroup(
            dialog_entregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_mesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_mesas.png"))); // NOI18N
        btn_mesas.setBorderPainted(false);
        btn_mesas.setContentAreaFilled(false);

        btn_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Productos.png"))); // NOI18N
        btn_producto.setBorderPainted(false);
        btn_producto.setContentAreaFilled(false);

        btn_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Clientes.png"))); // NOI18N
        btn_cliente.setBorderPainted(false);
        btn_cliente.setContentAreaFilled(false);

        btn_Factura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Proveedores.png"))); // NOI18N
        btn_Factura.setBorderPainted(false);
        btn_Factura.setContentAreaFilled(false);

        btn_configuracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Configuracion.png"))); // NOI18N
        btn_configuracion.setBorderPainted(false);
        btn_configuracion.setContentAreaFilled(false);

        btn_n1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_1.png"))); // NOI18N
        btn_n1.setBorderPainted(false);
        btn_n1.setContentAreaFilled(false);

        btn_n2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_2.png"))); // NOI18N
        btn_n2.setBorderPainted(false);
        btn_n2.setContentAreaFilled(false);

        btn_n3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_3.png"))); // NOI18N
        btn_n3.setBorderPainted(false);
        btn_n3.setContentAreaFilled(false);

        btn_n4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_4.png"))); // NOI18N
        btn_n4.setBorderPainted(false);
        btn_n4.setContentAreaFilled(false);

        btn_n5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_5.png"))); // NOI18N
        btn_n5.setBorderPainted(false);
        btn_n5.setContentAreaFilled(false);

        btn_n6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_6.png"))); // NOI18N
        btn_n6.setBorderPainted(false);
        btn_n6.setContentAreaFilled(false);

        btn_n7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_7.png"))); // NOI18N
        btn_n7.setBorderPainted(false);
        btn_n7.setContentAreaFilled(false);

        btn_n8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_8.png"))); // NOI18N
        btn_n8.setBorderPainted(false);
        btn_n8.setContentAreaFilled(false);

        btn_n9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_9.png"))); // NOI18N
        btn_n9.setBorderPainted(false);
        btn_n9.setContentAreaFilled(false);

        btn_n10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_10.png"))); // NOI18N
        btn_n10.setBorderPainted(false);
        btn_n10.setContentAreaFilled(false);

        btn_n11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_11.png"))); // NOI18N
        btn_n11.setBorderPainted(false);
        btn_n11.setContentAreaFilled(false);

        btn_n12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/numero_12.png"))); // NOI18N
        btn_n12.setBorderPainted(false);
        btn_n12.setContentAreaFilled(false);

        btn_Reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Reporte.png"))); // NOI18N
        btn_Reporte.setBorderPainted(false);
        btn_Reporte.setContentAreaFilled(false);

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Cerrar-19.png"))); // NOI18N
        btn_cerrar.setBorderPainted(false);
        btn_cerrar.setContentAreaFilled(false);

        javax.swing.GroupLayout jp_mesasLayout = new javax.swing.GroupLayout(jp_mesas);
        jp_mesas.setLayout(jp_mesasLayout);
        jp_mesasLayout.setHorizontalGroup(
            jp_mesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_mesasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_mesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_mesasLayout.createSequentialGroup()
                        .addComponent(btn_n1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_n2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_n3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_n4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_n5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_n6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_mesasLayout.createSequentialGroup()
                        .addComponent(btn_n7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_n8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_n9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_n10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_n11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_n12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jp_mesasLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btn_mesas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btn_Factura, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jp_mesasLayout.setVerticalGroup(
            jp_mesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_mesasLayout.createSequentialGroup()
                .addGroup(jp_mesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_mesasLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_mesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_Factura, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_mesas)
                        .addComponent(btn_configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_mesasLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btn_Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(jp_mesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_n6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_n2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_n1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_n3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_n4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_n5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_mesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_n11, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_n8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_n7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_n9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_n10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_n12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_mesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_mesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clientesActionPerformed

    public JButton getBtn_Factura() {
        return btn_Factura;
    }

    public void setBtn_Factura(JButton btn_Factura) {
        this.btn_Factura = btn_Factura;
    }

    public JButton getBtn_Reporte() {
        return btn_Reporte;
    }

    public void setBtn_Reporte(JButton btn_Reporte) {
        this.btn_Reporte = btn_Reporte;
    }

    public JButton getBtn_cliente() {
        return btn_cliente;
    }

    public void setBtn_cliente(JButton btn_cliente) {
        this.btn_cliente = btn_cliente;
    }

    public JButton getBtn_configuracion() {
        return btn_configuracion;
    }

    public void setBtn_configuracion(JButton btn_configuracion) {
        this.btn_configuracion = btn_configuracion;
    }

    public JButton getBtn_mesas() {
        return btn_mesas;
    }

    public void setBtn_mesas(JButton btn_mesas) {
        this.btn_mesas = btn_mesas;
    }

    public JButton getBtn_n1() {
        return btn_n1;
    }

    public void setBtn_n1(JButton btn_n1) {
        this.btn_n1 = btn_n1;
    }

    public JButton getBtn_n10() {
        return btn_n10;
    }

    public void setBtn_n10(JButton btn_n10) {
        this.btn_n10 = btn_n10;
    }

    public JButton getBtn_n11() {
        return btn_n11;
    }

    public void setBtn_n11(JButton btn_n11) {
        this.btn_n11 = btn_n11;
    }

    public JButton getBtn_n12() {
        return btn_n12;
    }

    public void setBtn_n12(JButton btn_n12) {
        this.btn_n12 = btn_n12;
    }

    public JButton getBtn_n2() {
        return btn_n2;
    }

    public void setBtn_n2(JButton btn_n2) {
        this.btn_n2 = btn_n2;
    }

    public JButton getBtn_n3() {
        return btn_n3;
    }

    public void setBtn_n3(JButton btn_n3) {
        this.btn_n3 = btn_n3;
    }

    public JButton getBtn_n4() {
        return btn_n4;
    }

    public void setBtn_n4(JButton btn_n4) {
        this.btn_n4 = btn_n4;
    }

    public JButton getBtn_n5() {
        return btn_n5;
    }

    public void setBtn_n5(JButton btn_n5) {
        this.btn_n5 = btn_n5;
    }

    public JButton getBtn_n6() {
        return btn_n6;
    }

    public void setBtn_n6(JButton btn_n6) {
        this.btn_n6 = btn_n6;
    }

    public JButton getBtn_n7() {
        return btn_n7;
    }

    public void setBtn_n7(JButton btn_n7) {
        this.btn_n7 = btn_n7;
    }

    public JButton getBtn_n8() {
        return btn_n8;
    }

    public void setBtn_n8(JButton btn_n8) {
        this.btn_n8 = btn_n8;
    }

    public JButton getBtn_n9() {
        return btn_n9;
    }

    public void setBtn_n9(JButton btn_n9) {
        this.btn_n9 = btn_n9;
    }

    public JButton getBtn_producto() {
        return btn_producto;
    }

    public void setBtn_producto(JButton btn_producto) {
        this.btn_producto = btn_producto;
    }

    public JPanel getJp_mesas() {
        return jp_mesas;
    }

    public void setJp_mesas(JPanel jp_mesas) {
        this.jp_mesas = jp_mesas;
    }

    public JButton getBtn_cancelar() {
        return btn_cancelar;
    }

    public void setBtn_cancelar(JButton btn_cancelar) {
        this.btn_cancelar = btn_cancelar;
    }

    public JButton getBtn_factura() {
        return btn_factura;
    }

    public void setBtn_factura(JButton btn_factura) {
        this.btn_factura = btn_factura;
    }

    public JButton getBtn_guardar() {
        return btn_guardar;
    }

    public void setBtn_guardar(JButton btn_guardar) {
        this.btn_guardar = btn_guardar;
    }

    public JDialog getDialog_mesas() {
        return dialog_mesas;
    }

    public void setDialog_mesas(JDialog dialog_mesas) {
        this.dialog_mesas = dialog_mesas;
    }

    public JTable getTb_mesas() {
        return tb_mesas;
    }

    public void setTb_mesas(JTable tb_mesas) {
        this.tb_mesas = tb_mesas;
    }

    public JTextField getTxt_buscar() {
        return txt_buscar;
    }

    public void setTxt_buscar(JTextField txt_buscar) {
        this.txt_buscar = txt_buscar;
    }

    public JButton getBtn_Imprimir() {
        return btn_Imprimir;
    }

    public void setBtn_Imprimir(JButton btn_Imprimir) {
        this.btn_Imprimir = btn_Imprimir;
    }

    public JButton getBtn_cancelar_d2() {
        return btn_cancelar_d2;
    }

    public void setBtn_cancelar_d2(JButton btn_cancelar_d2) {
        this.btn_cancelar_d2 = btn_cancelar_d2;
    }

    public JDialog getDialog_factura() {
        return dialog_factura;
    }

    public void setDialog_factura(JDialog dialog_factura) {
        this.dialog_factura = dialog_factura;
    }

    public JPanel getJp_factura() {
        return jp_factura_dialog;
    }

    public void setJp_factura(JPanel jp_factura) {
        this.jp_factura_dialog = jp_factura;
    }

    public JPanel getJp_mesas_dialog() {
        return jp_mesas_dialog;
    }

    public void setJp_mesas_dialog(JPanel jp_mesas_dialog) {
        this.jp_mesas_dialog = jp_mesas_dialog;
    }

    public JTable getTb_Factura() {
        return tb_Factura;
    }

    public void setTb_Factura(JTable tb_Factura) {
        this.tb_Factura = tb_Factura;
    }

    public JTextField getTxt_direccion_d() {
        return txt_direccion_d;
    }

    public void setTxt_direccion_d(JTextField txt_direccion_d) {
        this.txt_direccion_d = txt_direccion_d;
    }

    public JTextField getTxt_nombre_d() {
        return txt_nombre_d;
    }

    public void setTxt_nombre_d(JTextField txt_nombre_d) {
        this.txt_nombre_d = txt_nombre_d;
    }

    public JTextField getTxt_ruc_d() {
        return txt_ruc_d;
    }

    public void setTxt_ruc_d(JTextField txt_ruc_d) {
        this.txt_ruc_d = txt_ruc_d;
    }

    public JCheckBox getCb_Entrega() {
        return cb_Entrega;
    }

    public void setCb_Entrega(JCheckBox cb_Entrega) {
        this.cb_Entrega = cb_Entrega;
    }

    public JDialog getDialog_entrega() {
        return dialog_entrega;
    }

    public void setDialog_entrega(JDialog dialog_entrega) {
        this.dialog_entrega = dialog_entrega;
    }

    public JTextField getTxt_delivery() {
        return txt_delivery;
    }

    public void setTxt_delivery(JTextField txt_delivery) {
        this.txt_delivery = txt_delivery;
    }

    public JTextField getTxt_identrega() {
        return txt_identrega;
    }

    public void setTxt_identrega(JTextField txt_identrega) {
        this.txt_identrega = txt_identrega;
    }

    public JButton getBtn_cerrar() {
        return btn_cerrar;
    }

    public void setBtn_cerrar(JButton btn_cerrar) {
        this.btn_cerrar = btn_cerrar;
    }

    public JButton getBtn_clientes() {
        return btn_clientes;
    }

    public void setBtn_clientes(JButton btn_clientes) {
        this.btn_clientes = btn_clientes;
    }

    public JButton getBtn_regresar() {
        return btn_regresar;
    }

    public void setBtn_regresar(JButton btn_regresar) {
        this.btn_regresar = btn_regresar;
    }

    public JTable getTb_idproducto() {
        return tb_idproducto;
    }

    public void setTb_idproducto(JTable tb_idproducto) {
        this.tb_idproducto = tb_idproducto;
    }

    public JTextField getTxt_idcliente() {
        return txt_idcliente;
    }

    public void setTxt_idcliente(JTextField txt_idcliente) {
        this.txt_idcliente = txt_idcliente;
    }

    public JTextField getTxt_nmesa() {
        return txt_nmesa;
    }

    public void setTxt_nmesa(JTextField txt_nmesa) {
        this.txt_nmesa = txt_nmesa;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getJp_factura_dialog() {
        return jp_factura_dialog;
    }

    public void setJp_factura_dialog(JPanel jp_factura_dialog) {
        this.jp_factura_dialog = jp_factura_dialog;
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Factura;
    private javax.swing.JButton btn_Imprimir;
    private javax.swing.JButton btn_Reporte;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_cancelar_d2;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_cliente;
    private javax.swing.JButton btn_clientes;
    private javax.swing.JButton btn_configuracion;
    private javax.swing.JButton btn_factura;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_mesas;
    private javax.swing.JButton btn_n1;
    private javax.swing.JButton btn_n10;
    private javax.swing.JButton btn_n11;
    private javax.swing.JButton btn_n12;
    private javax.swing.JButton btn_n2;
    private javax.swing.JButton btn_n3;
    private javax.swing.JButton btn_n4;
    private javax.swing.JButton btn_n5;
    private javax.swing.JButton btn_n6;
    private javax.swing.JButton btn_n7;
    private javax.swing.JButton btn_n8;
    private javax.swing.JButton btn_n9;
    private javax.swing.JButton btn_producto;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JCheckBox cb_Entrega;
    private javax.swing.JDialog dialog_entrega;
    private javax.swing.JDialog dialog_factura;
    private javax.swing.JDialog dialog_mesas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jp_factura_dialog;
    private javax.swing.JPanel jp_mesas;
    private javax.swing.JPanel jp_mesas_dialog;
    private javax.swing.JTable tb_Factura;
    private javax.swing.JTable tb_idproducto;
    private javax.swing.JTable tb_mesas;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_delivery;
    private javax.swing.JTextField txt_direccion_d;
    private javax.swing.JTextField txt_idcliente;
    private javax.swing.JTextField txt_identrega;
    private javax.swing.JTextField txt_nmesa;
    private javax.swing.JTextField txt_nombre_d;
    private javax.swing.JTextField txt_ruc_d;
    // End of variables declaration//GEN-END:variables
    
    class FondoMesas extends JPanel{
        private Image imagen;
        
        public void paint(Graphics g){
            imagen=new ImageIcon(getClass().getResource("/Imagenes/Fondo_Mesas.png")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            
            super.paint(g);
        }
    }
    
    class FondoDialogMesas extends JDialog{
        private Image imagen;

        private FondoDialogMesas() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
        
        public void paint(Graphics g){
            imagen=new ImageIcon(getClass().getResource("/Imagenes/dialog_mesas.png")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            
            super.paint(g);
        }
    }

   class FondoDialogFactura extends JDialog{
        private Image imagen;

        private FondoDialogFactura() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
        
        public void paint(Graphics g){
            imagen=new ImageIcon(getClass().getResource("/Imagenes/dialog_factura.png")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            
            super.paint(g);
        }
    }
}
