/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author foraneoblack
 */
public class V_productos extends javax.swing.JFrame {

    
    public V_productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_producto = new javax.swing.JDialog();
        jp_dProductos = new FondoProductosDialog();
        txt_IdProducto = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        lb_foto = new javax.swing.JLabel();
        btn_examinar = new javax.swing.JButton();
        btn_Guardar_d = new javax.swing.JButton();
        btn_Cancelar_d = new javax.swing.JButton();
        btn_actualizar_d = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbb_tipo = new javax.swing.JComboBox<>();
        jp_productos = new FondoProductos();
        btn_Mesas = new javax.swing.JButton();
        btn_Productos = new javax.swing.JButton();
        btn_Clientes = new javax.swing.JButton();
        btn_Facturas = new javax.swing.JButton();
        btn_Configuracion = new javax.swing.JButton();
        btn_Reporte = new javax.swing.JButton();
        btn_Actualizar = new javax.swing.JButton();
        btn_Nuevo = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Productos = new javax.swing.JTable();
        btn_cerrar = new javax.swing.JButton();

        dialog_producto.setUndecorated(true);

        jp_dProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jp_dProductos.add(txt_IdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 128, -1));
        jp_dProductos.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 128, -1));
        jp_dProductos.add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 128, -1));
        jp_dProductos.add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 128, -1));
        jp_dProductos.add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 128, -1));

        lb_foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 138, 53)));
        jp_dProductos.add(lb_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 128, 122));

        btn_examinar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Examinar.png"))); // NOI18N
        btn_examinar.setBorderPainted(false);
        btn_examinar.setContentAreaFilled(false);
        jp_dProductos.add(btn_examinar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 60, 38));

        btn_Guardar_d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Guardar.png"))); // NOI18N
        btn_Guardar_d.setBorderPainted(false);
        btn_Guardar_d.setContentAreaFilled(false);
        jp_dProductos.add(btn_Guardar_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 56, 35));

        btn_Cancelar_d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Cancelar.png"))); // NOI18N
        btn_Cancelar_d.setBorderPainted(false);
        btn_Cancelar_d.setContentAreaFilled(false);
        jp_dProductos.add(btn_Cancelar_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 56, 35));

        btn_actualizar_d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Actualizar.png"))); // NOI18N
        btn_actualizar_d.setBorderPainted(false);
        btn_actualizar_d.setContentAreaFilled(false);
        jp_dProductos.add(btn_actualizar_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 80, 35));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(223, 117, 12));
        jLabel2.setText("Imagen");
        jp_dProductos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 100, 40));

        cbb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Arroces", "Ceviches", "Bebidas", "Asados", "Alcohol" }));
        jp_dProductos.add(cbb_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 130, -1));

        javax.swing.GroupLayout dialog_productoLayout = new javax.swing.GroupLayout(dialog_producto.getContentPane());
        dialog_producto.getContentPane().setLayout(dialog_productoLayout);
        dialog_productoLayout.setHorizontalGroup(
            dialog_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_dProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );
        dialog_productoLayout.setVerticalGroup(
            dialog_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_dProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        btn_Mesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_mesas.png"))); // NOI18N
        btn_Mesas.setBorderPainted(false);
        btn_Mesas.setContentAreaFilled(false);
        btn_Mesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MesasActionPerformed(evt);
            }
        });

        btn_Productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Productos.png"))); // NOI18N
        btn_Productos.setBorderPainted(false);
        btn_Productos.setContentAreaFilled(false);
        btn_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProductosActionPerformed(evt);
            }
        });

        btn_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Clientes.png"))); // NOI18N
        btn_Clientes.setBorderPainted(false);
        btn_Clientes.setContentAreaFilled(false);

        btn_Facturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Proveedores.png"))); // NOI18N
        btn_Facturas.setBorderPainted(false);
        btn_Facturas.setContentAreaFilled(false);
        btn_Facturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FacturasActionPerformed(evt);
            }
        });

        btn_Configuracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Configuracion.png"))); // NOI18N
        btn_Configuracion.setBorderPainted(false);
        btn_Configuracion.setContentAreaFilled(false);

        btn_Reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Reporte.png"))); // NOI18N
        btn_Reporte.setBorderPainted(false);
        btn_Reporte.setContentAreaFilled(false);

        btn_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Actualizar.png"))); // NOI18N
        btn_Actualizar.setBorderPainted(false);
        btn_Actualizar.setContentAreaFilled(false);

        btn_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Nuevo.png"))); // NOI18N
        btn_Nuevo.setBorderPainted(false);
        btn_Nuevo.setContentAreaFilled(false);

        btn_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Editar.png"))); // NOI18N
        btn_Editar.setBorderPainted(false);
        btn_Editar.setContentAreaFilled(false);

        btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Eliminar.png"))); // NOI18N
        btn_Eliminar.setBorderPainted(false);
        btn_Eliminar.setContentAreaFilled(false);

        tb_Productos.setBackground(new java.awt.Color(222, 138, 53));
        tb_Productos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(222, 138, 53), 2, true));
        tb_Productos.setForeground(new java.awt.Color(0, 0, 0));
        tb_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id_Producto", "Nombre", "Id_Tipo", "Cantidad", "Descripcion", "Precio", "Imagen"
            }
        ));
        jScrollPane1.setViewportView(tb_Productos);

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Cerrar-19.png"))); // NOI18N
        btn_cerrar.setBorderPainted(false);
        btn_cerrar.setContentAreaFilled(false);

        javax.swing.GroupLayout jp_productosLayout = new javax.swing.GroupLayout(jp_productos);
        jp_productos.setLayout(jp_productosLayout);
        jp_productosLayout.setHorizontalGroup(
            jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_productosLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btn_Mesas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btn_Facturas, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jp_productosLayout.createSequentialGroup()
                .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_productosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_productosLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btn_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jp_productosLayout.setVerticalGroup(
            jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_productosLayout.createSequentialGroup()
                .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_Mesas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_Configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_Facturas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_productosLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jp_productosLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(jp_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btn_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btn_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MesasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_MesasActionPerformed

    private void btn_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ProductosActionPerformed

    private void btn_FacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FacturasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_FacturasActionPerformed

    public JButton getBtn_Actualizar() {
        return btn_Actualizar;
    }

    public void setBtn_Actualizar(JButton btn_Actualizar) {
        this.btn_Actualizar = btn_Actualizar;
    }

    public JButton getBtn_Cancelar_d() {
        return btn_Cancelar_d;
    }

    public void setBtn_Cancelar_d(JButton btn_Cancelar_d) {
        this.btn_Cancelar_d = btn_Cancelar_d;
    }

    public JButton getBtn_Clientes() {
        return btn_Clientes;
    }

    public void setBtn_Clientes(JButton btn_Clientes) {
        this.btn_Clientes = btn_Clientes;
    }

    public JButton getBtn_Configuracion() {
        return btn_Configuracion;
    }

    public void setBtn_Configuracion(JButton btn_Configuracion) {
        this.btn_Configuracion = btn_Configuracion;
    }

    public JButton getBtn_Editar() {
        return btn_Editar;
    }

    public void setBtn_Editar(JButton btn_Editar) {
        this.btn_Editar = btn_Editar;
    }

    public JButton getBtn_Eliminar() {
        return btn_Eliminar;
    }

    public void setBtn_Eliminar(JButton btn_Eliminar) {
        this.btn_Eliminar = btn_Eliminar;
    }

    public JButton getBtn_Facturas() {
        return btn_Facturas;
    }

    public void setBtn_Facturas(JButton btn_Facturas) {
        this.btn_Facturas = btn_Facturas;
    }

    public JButton getBtn_Guardar_d() {
        return btn_Guardar_d;
    }

    public void setBtn_Guardar_d(JButton btn_Guardar_d) {
        this.btn_Guardar_d = btn_Guardar_d;
    }

    public JButton getBtn_Mesas() {
        return btn_Mesas;
    }

    public void setBtn_Mesas(JButton btn_Mesas) {
        this.btn_Mesas = btn_Mesas;
    }

    public JButton getBtn_Nuevo() {
        return btn_Nuevo;
    }

    public void setBtn_Nuevo(JButton btn_Nuevo) {
        this.btn_Nuevo = btn_Nuevo;
    }

    public JButton getBtn_Productos() {
        return btn_Productos;
    }

    public void setBtn_Productos(JButton btn_Productos) {
        this.btn_Productos = btn_Productos;
    }

    public JButton getBtn_Reporte() {
        return btn_Reporte;
    }

    public void setBtn_Reporte(JButton btn_Reporte) {
        this.btn_Reporte = btn_Reporte;
    }

    public JButton getBtn_actualizar_d() {
        return btn_actualizar_d;
    }

    public void setBtn_actualizar_d(JButton btn_actualizar_d) {
        this.btn_actualizar_d = btn_actualizar_d;
    }

    public JButton getBtn_examinar() {
        return btn_examinar;
    }

    public void setBtn_examinar(JButton btn_examinar) {
        this.btn_examinar = btn_examinar;
    }

    public JDialog getDialog_producto() {
        return dialog_producto;
    }

    public void setDialog_producto(JDialog dialog_producto) {
        this.dialog_producto = dialog_producto;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JPanel getJp_dProductos() {
        return jp_dProductos;
    }

    public void setJp_dProductos(JPanel jp_dProductos) {
        this.jp_dProductos = jp_dProductos;
    }

    public JPanel getJp_productos() {
        return jp_productos;
    }

    public void setJp_productos(JPanel jp_productos) {
        this.jp_productos = jp_productos;
    }

    public JLabel getLb_foto() {
        return lb_foto;
    }

    public void setLb_foto(JLabel lb_foto) {
        this.lb_foto = lb_foto;
    }

    public JTable getTb_Productos() {
        return tb_Productos;
    }

    public void setTb_Productos(JTable tb_Productos) {
        this.tb_Productos = tb_Productos;
    }

    public JTextField getTxt_IdProducto() {
        return txt_IdProducto;
    }

    public void setTxt_IdProducto(JTextField txt_IdProducto) {
        this.txt_IdProducto = txt_IdProducto;
    }

    public JTextField getTxt_cantidad() {
        return txt_cantidad;
    }

    public void setTxt_cantidad(JTextField txt_cantidad) {
        this.txt_cantidad = txt_cantidad;
    }

    public JTextField getTxt_descripcion() {
        return txt_descripcion;
    }

    public void setTxt_descripcion(JTextField txt_descripcion) {
        this.txt_descripcion = txt_descripcion;
    }

    public JTextField getTxt_nombre() {
        return txt_nombre;
    }

    public void setTxt_nombre(JTextField txt_nombre) {
        this.txt_nombre = txt_nombre;
    }

    public JTextField getTxt_precio() {
        return txt_precio;
    }

    public void setTxt_precio(JTextField txt_precio) {
        this.txt_precio = txt_precio;
    }

    public JButton getBtn_cerrar() {
        return btn_cerrar;
    }

    public void setBtn_cerrar(JButton btn_cerrar) {
        this.btn_cerrar = btn_cerrar;
    }

    public JComboBox<String> getCbb_tipo() {
        return cbb_tipo;
    }

    public void setCbb_tipo(JComboBox<String> cbb_tipo) {
        this.cbb_tipo = cbb_tipo;
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_Cancelar_d;
    private javax.swing.JButton btn_Clientes;
    private javax.swing.JButton btn_Configuracion;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Facturas;
    private javax.swing.JButton btn_Guardar_d;
    private javax.swing.JButton btn_Mesas;
    private javax.swing.JButton btn_Nuevo;
    private javax.swing.JButton btn_Productos;
    private javax.swing.JButton btn_Reporte;
    private javax.swing.JButton btn_actualizar_d;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_examinar;
    private javax.swing.JComboBox<String> cbb_tipo;
    private javax.swing.JDialog dialog_producto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jp_dProductos;
    private javax.swing.JPanel jp_productos;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JTable tb_Productos;
    private javax.swing.JTextField txt_IdProducto;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables

    class FondoProductos extends JPanel{
        private Image imagen;
        
        public void paint(Graphics g){
            imagen=new ImageIcon(getClass().getResource("/Imagenes/Fondo_productos.png")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            
            super.paint(g);
        }
    }
    
    class FondoProductosDialog extends JPanel{
        private Image imagen;
        
        public void paint(Graphics g){
            imagen=new ImageIcon(getClass().getResource("/Imagenes/dialog_productos.png")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            
            super.paint(g);
        }
    }
}
